name:  Risk Item (in yaml)
description: GMAGAO-X Risk
title: "[Risk]: "
labels: "risk"

body:

- type: input
  attributes:
    label: "Risk creation date:"
    
- type: input
  attributes:
    label: "Last modified:"
    
- type: dropdown
  attributes:
    label: "Risk Type:"
    options:
      - Technical
      - Schedule
      - Cost
      - Safety
        
- type: dropdown
  attributes:
    label: "Risk Approach:"
    options:
      - Mitigate
      - Watch
      - Accept (with residual risk)
      - Close (with no residual risk)
      - Reject
      - Candidate risk
        
- type: dropdown
  attributes:
    label: "Risk Owner:"
    options:
      - Doug Kelly
      - Jared Males
      - Sebastiaan Haffert
      - Laird Close
      - Fernando Coronado
      - Oli Durney
      - Victor Gasho
      - Olivier Guyon

- type: markdown
  attributes:
    value: |
      Please capture all details needed to characterize the risk and its mitigations.

- type: textarea
  attributes: 
    label: "Risk Statement:"
    description: Provide an If...Then... statement for the risk
    placeholder:  If Jack and Jill go up the hill and Jack falls down, then Jill comes tumbling after.

- type: textarea
  attributes: 
    label: "Risk Effects:"
    description: Describe what would happen if the risk were realized

- type: dropdown
  attributes:
    label: "Initial Risk Likelihood:"
    options: 
      - very low (<2%)
      - low (2-15%)
      - moderate (15-25%)
      - high (25-50%)
      - very high (>50%)

- type: dropdown
  attributes:
    label: "Initial Risk Consequence:"
    options: 
      - very low (negligible impact)
      - low (decrease in margins)
      - moderate (major loss of capability)
      - high (loss of one or more level-1 reqs)
      - very high (loss of instrument or mission)

- type: dropdown
  attributes:
    label: "Current Risk Likelihood:"
    options: 
      - very low (<2%)
      - low (2-15%)
      - moderate (15-25%)
      - high (25-50%)
      - very high (>50%)

- type: dropdown
  attributes:
    label: "Current Risk Consequence:"
    options: 
      - very low (negligible impact)
      - low (decrease in margins)
      - moderate (major loss of capability)
      - high (loss of one or more level-1 reqs)
      - very high (loss of instrument or mission)

- type: dropdown
  attributes:
    label: "Target Risk Likelihood:"
    options: 
      - very low (<2%)
      - low (2-15%)
      - moderate (15-25%)
      - high (25-50%)
      - very high (>50%)

- type: dropdown
  attributes:
    label: "Target Risk Consequence:"
    options: 
      - very low (negligible impact)
      - low (decrease in margins)
      - moderate (major loss of capability)
      - high (loss of one or more level-1 reqs)
      - very high (loss of instrument or mission)
       
- type: textarea
  attributes: 
    label: "Initial Risk Notes:"

- type: textarea
  attributes:
    label: "Estimated cost if risk is realized:"

- type: textarea
  attributes:
    label: "Explanation for cost risk:"

- type: textarea
  attributes:
    label: "Risk mitigation list:"
    value: |
      1.
      2.
      3.
      4.


